### ISSUE TITLE
(یک خارج به چند ایران)درخواست مولتی سرور 

### ISSUE THREAD

**Issue by ramram2020** [Azumi67/Backhaul_script#1]
با سلام.
ممنون از شما.
آیا  امکان ارتباط یک سرور خارج به چند سرور ایران هم هست ؟
چون در توضیحات این مورد را نزدید. اما در مثالی که قرار دادید بنظر این امکان وجود داره

**Comment by Azumi67** [comment]
سلام فکر نکنم مشکلی باشه.
