### ISSUE TITLE
مشکل 

### ISSUE THREAD

**Issue by alphamanrays** [Azumi67/Backhaul_script#3]
سلام وقت بخیر خسته نباشید متاسفانه رو بعضی از سرور ها کار نمیکنه بنظرتون مشکل از کجاس ؟

**Comment by Azumi67** [comment]
سلام ممکنه از خود محدودیت سرور باشد . توسط آی‌پی ۶ یا لوکال هم تست نمایید تا اسکریپت بعدا به نسخه آخر هم آپدیت شود

**Comment by lonel1370** [comment]
سلام الان اسکریپت تو سرور ایران اجرا نمیشه و کانکت نمیشه:
185.199.109.133|:443
چیکار باید کرد؟ با فیلترشکنم باز نمیشه
