### ISSUE TITLE
ip local

### ISSUE THREAD

**Issue by Ghasedaak** [Azumi67/Backhaul_script#4]
سلام وقت بخیر ممنون از وقتی که میذارید و به همه ما کمک میکنید
من از طریق اسکریپت شما از روش vxlan ایپی لوکال گرفتم ولی نتونستم  داخل این تانل استفاده کنم
ممکنه بگید چطور میتونم این تانل رو بر بستر ایپی لوکال استفاده کنم؟

لطفا یه امزشی چیزی بگید یا روش رو به من بگید من انجام بدم سپاس

**Comment by Azumi67** [comment]
سلام. باید اول یک ارتباط لوکال‌ از طریق اسکریپت یا به صورت manual ایجاد کنید و در کلاینت خارج داخل backhaul آدرس آی‌پی لوکال ایران را بدهید . اینطوری باید کار کنه.
مطمئن بشید که ارتباط لوکال‌ فعال است و کار میکند .
