### ISSUE TITLE
تغییر زمان ری استارت خودکار

### ISSUE THREAD

**Issue by hatinati2** [Azumi67/Backhaul_script#5]
سلام وقت بخیر
با تشکر از زحمات شما 
برای تغییر (ادیت)زمان ری استارت خودکار آیا راهی هست؟ یا باید از اول کانفیگ انجام داد؟
مرسی متشکرم

**Comment by Azumi67** [comment]
سلام. من احتمالا یادم رفته اضافه کنم . بعدا اضافه میکنم که راحت عوض کنید

**Comment by hatinati2** [comment]
> سلام. من احتمالا یادم رفته اضافه کنم . بعدا اضافه میکنم که راحت عوض کنید

سلام مرسی متشکرم 
لطف می کنید
