### ISSUE TITLE
No module named 'requests

### ISSUE THREAD

**Issue by sarboy1371** [Azumi67/Backhaul_script#7]
سلام .موقع اجرای اسکریپت این خطا رو میگیرم
No module named 'requests
![backhaul](https://github.com/user-attachments/assets/4b6271c0-6e3a-4b6a-9aea-bd38dd1be730)

**Comment by Azumi67** [comment]
سلام
`sudo apt update -y && sudo apt install -y python3 python3-pip curl && pip3 install --upgrade pip && pip3 install netifaces colorama requests`
 اگر externally managed بودید 
`bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/Backhaul_script/refs/heads/main/managed.sh)"`

**Comment by sarboy1371** [comment]
> سلام `sudo apt update -y && sudo apt install -y python3 python3-pip curl && pip3 install --upgrade pip && pip3 install netifaces colorama requests` اگر externally managed بودید `bash -c "$(curl -fsSL https://raw.githubusercontent.com/Azumi67/Backhaul_script/refs/heads/main/managed.sh)"`

حل شد.مررررررسی
